/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-03-01 09:40:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class categoryHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1548321130691L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("배달의 신", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#category-nav{\r\n");
      out.write("     position: relative;\r\n");
      out.write("    top: 88px;\r\n");
      out.write("    width: 89%;\r\n");
      out.write("    left: 7%;\r\n");
      out.write("    pointer:cursor;\r\n");
      out.write("}\r\n");
      out.write("#search-container{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 72px;\r\n");
      out.write("    left: 39%;\r\n");
      out.write("}\r\n");
      out.write("hr{\r\n");
      out.write("    top: 102px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div id=\"category-container\">  \t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 검색창 -->\r\n");
      out.write("    <div id=\"search-container\">\r\n");
      out.write("\t <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t   <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" id=\"search\">\r\n");
      out.write("\t   <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("\t </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 카테고리란 -->\r\n");
      out.write("\t<div id =\"category-nav-container\">\r\n");
      out.write("\t\t<ul class=\"nav nav-pills nav-fill\" id=\"category-nav\">\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"1\" id=\"chicken\">치킨</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"2\" id=\"pizza\">피자</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\"onclick=\"categoryList(this);\" name=\"3\" id=\"bossam\">보쌈/족발</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"4\" id=\"bunsik\">분식</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t    <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"5\" id=\"china\">중식</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"6\" id=\"japan\">일식</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t    <a class=\"nav-link\" onclick=\"categoryList(this);\" name=\"7\" id=\"korea\">한식</a>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t</ul>\t\t\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\t\r\n");
      out.write("\tfunction categoryList(item){\r\n");
      out.write("\t\tvar categoryNo = $(item).attr(\"name\");\r\n");
      out.write("\t    location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/storeInfo/storeInfoList.do?categoryNo=\"+categoryNo;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//치킨눌렀을 시\r\n");
      out.write("\t$(\"#chicken\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//피자\r\n");
      out.write("\t$(\"#pizza\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//보쌈\r\n");
      out.write("\t$(\"#bossam\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//분식\r\n");
      out.write("\t\t$(\"#bunsik\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//중식\r\n");
      out.write("\t\t$(\"#china\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//일식\r\n");
      out.write("\t\t$(\"#japan\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").addClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").removeClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//한식\r\n");
      out.write("\t\t$(\"#korea\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#all\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#chicken\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#pizza\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bossam\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#bunsik\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#china\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#japan\").removeClass(\"active\");\r\n");
      out.write("\t\t$(\"#korea\").addClass(\"active\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
